#!/bin/bash

basepath=$(cd `dirname $0`; pwd)

ps aux|grep $basepath|awk '{print $2}'|xargs kill 

cd $basepath

./killall

rm -rf ENV

virtualenv ENV

ENV/bin/pip install -r requirements.txt

./serverd
